// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System',
      items: [
        'module-1/index',
        'module-1/robotic-middleware-fundamentals',
        'module-1/core-communication-concepts',
        'module-1/ai-agents-robot-models',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin',
      items: [
        'module-2/index',
        'module-2/digital-twin-fundamentals',
        'module-2/physics-simulation-gazebo',
        'module-2/sensors-interaction',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain',
      items: [
        'module-3/index',
        'module-3/nvidia-isaac-overview',
        'module-3/perception-localization-isaac-ros',
        'module-3/navigation-motion-planning',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4/index',
        'module-4/vla-fundamentals',
        'module-4/voice-to-action',
        'module-4/cognitive-planning',
      ],
    },
    // Add more modules as needed
  ],
};

export default sidebars;
